In [10]:
import numpy as np

# # Matriz de prueba, para saber si estoy bien
# A = ([[4, 2, 5],
#       [2, 5, 8],
#       [5, 4, 3]])

# B = ([[60.7],
#       [96.2],
#       [52.3]])

F0 = 2
w = 3
m1, m2, m3 = (0.5, 0.7, 0.6)
L1, L2, L3 = (1, 0.8, 1.2)
k1, k2 = (50, 40)
g = 9.81
t = np.linspace(0,20, 100)

# Matriz que se pide
A = ([[(-m1*L1*w**2 + k1 + m1*g), -k1, 0],
      [-k1, (-m2*L2*w**2 + k1 + k2 + m2*g), -k2],
      [0, -k2, k2 + m3 * (-L3*w**2 + g)]])

B = ([[F0],
      [0],
      [0]])


In [12]:
def Decomposer(matrix, vector):
    matrix0 = np.array(matrix, dtype = "float")
    n, m = matrix0.shape
    L = np.zeros((n, m), dtype = "float")
    U = np.copy(matrix0)
    x = np.zeros(n, dtype = "float")
    y = np.zeros(n, dtype = "float")

    # # Pivoteo Parcial
    # for i in range(n):
    #     column = matrix0[i:, i]
    #     wheremax = np.argmax(column)

    #     if wheremax != 0:
    #         temp = np.copy(matrix0[i, :])
    #         matrix0[i, :] = matrix0[wheremax + i, :]
    #         matrix0[wheremax + i, :] = temp

    # U = np.copy(matrix0)

    # Descomposición LU en situ
    for i in range(n):
        L[i, i] = 1
        pivot = U[i, i]
        for j in range(i + 1, m):
            factor = U[j, i] / pivot
            L[j, i] = factor
            U[j, :]-= U[i, :] * factor
            
    # Encontrando Y para luego encontrar X usando sustitución hacia adelanta/atrás
    for i in range(n):
        y[i] = (vector[i] - np.dot(L[i, :], y)) / L[i, i]
        
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, :], x)) / U[i, i]
            
    return L, U, x
# Verificaciones
results = Decomposer(A, B)
print(results[0])
print("\n")
print(results[1])
print("\n")
print(results[0]@results[1])
print("\n")
print(results[2])
print("\n")
print(A@np.concatenate([results[2]]))
print("\n")
print("Las constantes que acompañan a las funciones theta_k = A_kCos(wt) son: ")
print("\n")
print(results[2])

[[ 1.          0.          0.        ]
 [-0.99196508  1.          0.        ]
 [ 0.         -0.94722207  1.        ]]


[[ 50.405      -50.           0.        ]
 [  0.          42.22874586 -40.        ]
 [  0.           0.           1.51711726]]


[[ 50.405 -50.      0.   ]
 [-50.     91.827 -40.   ]
 [  0.    -40.     39.406]]


[1.25015907 1.22028536 1.23867975]


[2.00000000e+00 8.88178420e-15 6.27028599e-15]


Las constantes que acompañan a las funciones theta_k = A_kCos(wt) son: 


[1.25015907 1.22028536 1.23867975]


/tmp/ipykernel_2803/594641619.py:32: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i, :], y)) / L[i, i]


In [6]:
originalPrice = float(input("Digite el precio original: "))
cuotesN = int(input("Digite el número de cuotas: "))
bankFee = float(input("Ingrese los intereses del banco: "))
cuotePrice = originalPrice / cuotesN
totalPrice = 0

for i in range(cuotesN):
    totalPrice += cuotePrice
    cuotePrice *= ((bankFee/100 + 1)**(1/cuotesN))
    print(i,".", totalPrice)

totalPrice = round(totalPrice, 2)
diff = round(totalPrice - originalPrice, 2)

print("\n Su precio a pagar en total de cuotas sería de $", totalPrice, ". Estaría perdiendo: $", diff)

Digite el precio original:  160000
Digite el número de cuotas:  1
Ingrese los intereses del banco:  27.6


0 . 160000.0

 Su precio a pagar en total de cuotas sería de $ 160000.0 . Estaría perdiendo: $ 0.0
