In [40]:
import numpy as np

# # Matriz de prueba, para saber si estoy bien
# A = ([[4, 2, 5],
#       [2, 5, 8],
#       [5, 4, 3]])

# B = ([[60.7],
#       [96.2],
#       [52.3]])

F0 = 2
w = 3
m1, m2, m3 = (0.5, 0.7, 0.6)
L1, L2, L3 = (1, 0.8, 1.2)
k1, k2 = (50, 40)
g = 9.81
t = np.linspace(0,20, 100)

# Matriz que se pide
A = ([[-m1*L1*w**2, -k1, 0],
      [-k1, (-m2*L2*w**2 + k1 + k2 + m2*g), -k2],
      [0, -k2, m3 * (-L3*w**2 + g)]])

B = ([[F0],
      [0],
      [0]])


In [49]:
def Decomposer(matrix, vector):
    matrix0 = np.array(matrix, dtype = "float")
    n, m = matrix0.shape
    L = np.zeros((n, m), dtype = "float")
    U = np.copy(matrix0)
    x = np.zeros(n, dtype = "float")
    y = np.zeros(n, dtype = "float")

    # # Pivoteo Parcial
    # for i in range(n):
    #     column = matrix0[i:, i]
    #     wheremax = np.argmax(column)

    #     if wheremax != 0:
    #         temp = np.copy(matrix0[i, :])
    #         matrix0[i, :] = matrix0[wheremax + i, :]
    #         matrix0[wheremax + i, :] = temp

    # U = np.copy(matrix0)

    # Descomposición LU en situ
    for i in range(n):
        L[i, i] = 1
        pivot = U[i, i]
        for j in range(i + 1, m):
            factor = U[j, i] / pivot
            L[j, i] = factor
            U[j, :]-= U[i, :] * factor
            
    # Encontrando Y para luego encontrar X usando sustitución hacia adelanta/atrás
    for i in range(n):
        y[i] = (vector[i] - np.dot(L[i, :], y)) / L[i, i]
        
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, :], x)) / U[i, i]
            
    return L, U, x
# Verificaciones
results = Decomposer(A, B)
print(results[0])
print("\n")
print(results[1])
print("\n")
print(results[0]@results[1])
print("\n")
print(results[2])
print("\n")
print(A@np.concatenate([results[2]]))

print("Las constantes que acompañan a las funciones theta_k = A_kCos(wt) son: \n")
print("\n")
print(results[2])

[[ 1.          0.          0.        ]
 [11.11111111  1.          0.        ]
 [-0.         -0.06178727  1.        ]]


[[ -4.5        -50.           0.        ]
 [  0.         647.38255556 -40.        ]
 [  0.           0.          -3.06549075]]


[[ -4.5   -50.      0.   ]
 [-50.     91.827 -40.   ]
 [  0.    -40.     -0.594]]


[-0.37054002 -0.0066514   0.44790558]


[ 2.00000000e+00  2.77555756e-15 -1.11022302e-16]
Las constantes que acompañan a las funciones theta_k = A_kCos(wt) son: 



[-0.37054002 -0.0066514   0.44790558]


/tmp/ipykernel_2235/1634434788.py:32: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i, :], y)) / L[i, i]
