In [1]:
import numpy as np
import matplotlib.pyplot as plt

A1 = np.array([[1,2,-3],
              [4,2,-6],
              [1,-2,9]])

A2 = np.array([[1,2],
              [2,3],
              [3,4]])

B = np.array([[3],
              [5],
              [7]])


In [14]:
def Factorizer(matrix, vector):

    n, m = matrix.shape
    Q = np.zeros((n, m), dtype = 'float')
    R = np.zeros((m, m), dtype = 'float')
    X = np.zeros(m, dtype='float')
    u = np.zeros((n, m), dtype = 'float')
    e = np.copy(Q)
    u[:,0] = matrix[:,0]
    e[:,0] = u[:,0] / np.linalg.norm(u[:,0])
    
    for i in range(m):
        u[:,i] = matrix[:,i]
        
        for j in range(i):
            u[:,i] = u[:,i] - (matrix[:,i]@e[:,j]*e[:,j])
            
        e[:,i] = u[:,i] / np.linalg.norm(u[:,i])
    
    Q = e
    for i in range(n):
        for j in range(i,m):
            R[i,j] = e[:,i]@matrix[:,j]

    for i in range(m-1, -1, -1):
        sum = 0

        for j in range(m-1, -1, -1):
            sum += R[i,j]*X[j]

        X[i] = ((Q.T@B)[i] - sum) / R[i,i]

    X = np.transpose([X])

    residual = B - np.dot(Q@R,X)

    err = 0

    for i in range(n):
        err += residual[i] ** 2

    err = np.sqrt(err)
               
    return Q, R, X, err

results = Factorizer(A2, B)

print('Q, R y X se presentan a continuación: \n')
print(results[0])
print(results[1])
print(results[2])
print('\n')
print('Veridicación de la factorización: \n')
print(A2)
print(results[0]@results[1])
A2 == results[0]@results[1]
print('\n')
print('Verificación de resultados RX = Q.TB: \n')
print(results[1]@results[2])
print(results[0].T@B)
print('\n')
print('Verificación de resultado (QR)X = B: \n')
print(A2@results[2])
print('\n')
print('Error del método: \n')
print(results[3])


Q, R y X se presentan a continuación: 

[[ 0.26726124  0.87287156]
 [ 0.53452248  0.21821789]
 [ 0.80178373 -0.43643578]]
[[3.74165739 5.34522484]
 [0.         0.65465367]]
[[1.]
 [1.]]


Veridicación de la factorización: 

[[1 2]
 [2 3]
 [3 4]]
[[1. 2.]
 [2. 3.]
 [3. 4.]]


Verificación de resultados RX = Q.TB: 

[[9.08688223]
 [0.65465367]]
[[9.08688223]
 [0.65465367]]


Verificación de resultado (QR)X = B: 

[[3.]
 [5.]
 [7.]]


Error del método: 

[1.25607397e-15]


/tmp/ipykernel_6893/1154140068.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X[i] = ((Q.T@B)[i] - sum) / R[i,i]
