In [2]:
import numpy as np
import matplotlib.pyplot as plt

A1 = np.array([[1,2,-3],
              [4,2,-6],
              [1,-2,9]])

A = np.array([[4, 2, 5],
             [2, 5, 8],
             [5, 4, 3]])

B1 = np.array([[60.7],
             [92.9],
             [56.3]])

A2 = np.array([[1,2],
              [2,3],
              [3,4]])

B = np.array([[3],
              [5],
              [7]])


In [3]:
def Factorizer(matrix, vector):

    n, m = matrix.shape
    Q = np.zeros((n, m), dtype = 'float')
    R = np.zeros((m, m), dtype = 'float')
    X = np.zeros(m, dtype='float')
    u = np.zeros((n, m), dtype = 'float')
    e = np.copy(Q)
    u[:,0] = matrix[:,0]
    e[:,0] = u[:,0] / np.linalg.norm(u[:,0])
    
    for i in range(m):
        u[:,i] = matrix[:,i]
        
        for j in range(i):
            u[:,i] = u[:,i] - (matrix[:,i]@e[:,j]*e[:,j])
            
        e[:,i] = u[:,i] / np.linalg.norm(u[:,i])
    
    Q = np.copy(e)
    for i in range(n):
        for j in range(i,m):
            R[i,j] = e[:,i]@matrix[:,j]

    for i in range(m-1, -1, -1):
        sum = 0

        for j in range(m-1, -1, -1):
            sum += R[i,j]*X[j]

        X[i] = ((Q.T@B)[i] - sum) / R[i,i]

    X = np.transpose([X])

    residual = B - np.dot(Q@R,X)

    err = 0

    for i in range(n):
        err += residual[i] ** 2

    # err = np.sqrt(err)
               
    return Q, R, X, err

results = Factorizer(A, B1)

print('Q, R y X se presentan a continuación: \n')
print(results[0])
print(results[1])
print(results[2])
print('\n')
print('Veridicación de la factorización: \n')
print(A)
print(results[0]@results[1])
A == results[0]@results[1]
print('\n')
print('Verificación de resultados RX = Q.TB: \n')
print(results[1]@results[2])
print(results[0].T@B1)
print('\n')
print('Verificación de resultado (QR)X = B: \n')
print(A1@results[2])
print('\n')
print('Error del método: \n')
print(results[3])


Q, R y X se presentan a continuación: 

[[ 0.59628479 -0.38343996  0.70527884]
 [ 0.2981424   0.9214928   0.24892194]
 [ 0.74535599 -0.06184515 -0.66379185]]
[[6.70820393 5.66470554 7.60263112]
 [0.         3.59320346 5.26920714]
 [0.         0.         3.52639421]]
[[ 0.51764706]
 [ 1.37647059]
 [-0.36470588]]


Veridicación de la factorización: 

[[4 2 5]
 [2 5 8]
 [5 4 3]]
[[4. 2. 5.]
 [2. 5. 8.]
 [5. 4. 3.]]


Verificación de resultados RX = Q.TB: 

[[ 8.49705831]
 [ 3.02422804]
 [-1.28609671]]
[[105.85545805]
 [ 58.84999341]
 [ 28.56379308]]


Verificación de resultado (QR)X = B: 

[[ 4.36470588]
 [ 7.01176471]
 [-5.51764706]]


Error del método: 

[1.57772181e-30]


/tmp/ipykernel_118423/4030947114.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X[i] = ((Q.T@B)[i] - sum) / R[i,i]
