In [1]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[4, 2, 5],
             [2, 5, 8],
             [5, 4, 3]])

B = np.array([[60.7],
             [92.9],
             [56.3]])

In [2]:
AB = np.concatenate((A,B),axis = 1)
AB0 = np.copy(AB)

In [3]:
n, m = AB.shape

for i in range (n):
    
    column = np.abs(AB[i:,i])
    wheremax = np.argmax(column)
    
    if wheremax != 0:

        temp = np.copy(AB[i,:])
        AB[i,:] = AB[wheremax+i,:]
        AB[wheremax+i,:] = temp

print(AB0)
print("\n")
print(AB)

[[ 4.   2.   5.  60.7]
 [ 2.   5.   8.  92.9]
 [ 5.   4.   3.  56.3]]


[[ 5.   4.   3.  56.3]
 [ 2.   5.   8.  92.9]
 [ 4.   2.   5.  60.7]]


In [4]:
for i in range(n):
    
    pivot = AB[i,i]
    forward = i + 1

    for k in range(forward, n):
        
        factor = AB[k, i] / pivot
        AB[k,:] -= AB[i, :] * factor

print(AB)

[[ 5.    4.    3.   56.3 ]
 [ 0.    3.4   6.8  70.38]
 [ 0.    0.    5.   40.5 ]]


In [5]:
lastrow = n - 1
lastcolumn = m - 1

x = np.zeros(n, dtype = "float")

for i in range(lastrow, -1, -1):
    sum = 0
    for j in range(i + 1, lastcolumn):
        sum += AB[i,j] * x[j]
        print(x)
    
    b = AB[i, lastcolumn]
    x[i] = (b - sum) / (AB[i,i])

results = np.transpose([x])
print(results)

[0.  0.  8.1]
[0.  4.5 8.1]
[0.  4.5 8.1]
[[2.8]
 [4.5]
 [8.1]]


In [6]:
np.dot(A,np.transpose([x]))

array([[60.7],
       [92.9],
       [56.3]])