In [1]:
import numpy as np

def Decomposer(matrix, vector):
    matrix0 = np.array(matrix, dtype = "float")
    n, m = matrix0.shape
    L = np.zeros((n,m), dtype = "float")
    U = np.copy(matrix0)
    x = np.zeros(n, dtype = "float")
    y = np.zeros(n, dtype = "float")
    
    for i in range(n):
        pivot = matrix0[i, i]
        forward = i + 1
        L[i,i] = 1
        
        for j in range(forward, n):
            factor = matrix0[j, i] / pivot
            L[j, i] = factor
            matrix0[j, :] -= matrix0[i, :] * factor
            U[j, :] = np.copy(matrix0[j, :])

    for i in range(n):
        y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]

    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i,:], x)) / U[i,i]

    det = np.prod(np.diag(U))

    return L, U, x, det
    
def Factorizer(matrix, vector):
    matrix0 = np.array(matrix, dtype = "float")
    n, m = matrix0.shape
    Q = np.zeros((n,m), dtype = "float")
    R = np.zeros((m,m), dtype = "float")
    u = np.zeros((n,m), dtype = "float")
    e = np.zeros((n,m), dtype = "float")
    x = np.zeros(n, dtype = "float")
    u[:,0] = matrix0[:,0]
    e[:,0] = u[:,0] / np.linalg.norm(u[:,0])

    for i in range(m):
        u[:,i] = matrix0[:,i]
        
        for j in range(i):
            u[:,i] -= ((matrix0[:,i]@e[:,j]) * e[:,j])
            
        e[:,i] = u[:,i] / np.linalg.norm(u[:,i])

    Q = np.copy(e)
        
    for i in range(n):
        for j in range(i, m):
            if i <= j:
                R[i,j] = (matrix0[:,j]@e[:,i])
                          
    for i in range(n - 1, -1, -1):
        x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]

    return Q, R, x

In [2]:
# Primer Punto - Kirchoff
R1, R2, R3, R4, R5 = (2, 1, 3, 1, 4)
V1, V2 = (10, 5)
A = np.array([[R1+R2, -R2, 0],
              [-R2, R2+R3+R4, -R4],
              [0, -R4, R4+R5]])
B = np.array([[V1],
              [0],
              [V2]])

_Decomposer= Decomposer(A, B)
print("Las corrientes que están presentes en el circuito son:\n", _Decomposer[2])

_Factorizer= Factorizer(A, B)
print("Las corrientes que están presentes en el circuito son:\n", _Factorizer[2])

Las corrientes que están presentes en el circuito son:
 [3.65671642 0.97014925 1.19402985]
Las corrientes que están presentes en el circuito son:
 [3.65671642 0.97014925 1.19402985]


/tmp/ipykernel_90626/577170648.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]
/tmp/ipykernel_90626/577170648.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]


In [3]:
# Segundo punto - temperaturas
k1, k2, k3 = (2, 1, 3)
Q1, Q2, Q3= (10, 15, 5)
A = np.array([[k1+k2, -k1, -k2],
              [-k1, k1+k3, -k3],
              [-k2, -k3, k2+k3]])
B = np.array([[Q1],
              [Q2],
              [Q3]])

_Decomposer= Decomposer(A, B)
print("Las temperaturas son (LU):\n", _Decomposer[2])

_Factorizer= Factorizer(A, B)
print("Las temperaturas son (QR):\n", _Factorizer[2])

# El método parece no funcionar, lo cual tiene relación con el hecho de que la matriz A tiene un determinate igual a cero:
print(np.linalg.det(A)) # Casi 0

# Por tanto al intentar descomponerla se daña

Las temperaturas son (LU):
 [6.75539944e+16 6.75539944e+16 6.75539944e+16]
Las temperaturas son (QR):
 [ 0.38277512  0.83732057 -0.52631579]
4.884981308350685e-15


/tmp/ipykernel_90626/577170648.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]
/tmp/ipykernel_90626/577170648.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]


In [7]:
# Tercer punto - vibraciones
a11, a22, a33, a12, a21, a23, a32 = (20, 24, 28, 7, 10, 4, 2)
f1, f2, f3= (1, 2, 1)
A = np.array([[a11, a12, 0],
              [a21, a22, a23],
              [0, a32, a33]])
B = np.array([[f1],
              [f2],
              [f3]])

_Decomposer= Decomposer(A, B)
print("Las amplitudes son (LU):\n", _Decomposer[2])

_Factorizer= Factorizer(A, B)
print("Las amplitudes son (QR):\n", _Factorizer[2])

Las amplitudes son (LU):
 [0.02650177 0.06713781 0.03091873]
Las amplitudes son (QR):
 [0.02650177 0.06713781 0.03091873]


/tmp/ipykernel_90626/577170648.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]
/tmp/ipykernel_90626/577170648.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]


In [5]:
# Cuarto punto - flujo de calor
k1, k2, k3 = (5, 2, 1)
Q1, Q2, Q3= (20, 15, 10)
A = np.array([[k1, -k1, 0],
              [-k2, k2+k3, -k3],
              [0, -k3, k3]])
B = np.array([[Q1],
              [Q2],
              [Q3]])

_Decomposer= Decomposer(A, B)
print("Las temperaturas son (LU):\n", _Decomposer[2])

_Factorizer= Factorizer(A, B)
print("Las temperaturas son (QR):\n", _Factorizer[2])

# Parece que esta matriz sufre del mismo problema que tiene la del punto 2, lo cual hace que el resultado sea completamente incosistente con la realidad

print(np.linalg.det(A))

Las temperaturas son (LU):
 [nan inf inf]
Las temperaturas son (QR):
 [54.30555556 51.52777778 46.25      ]
0.0


/tmp/ipykernel_90626/577170648.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]
/tmp/ipykernel_90626/577170648.py:26: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (y[i] - np.dot(U[i,:], x)) / U[i,i]
/tmp/ipykernel_90626/577170648.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]


In [6]:
# Verificador de relaciones entre los resutlados y la matriz original. Ejecute la celda que contenga las matrices a evaluar y luego ejecute esta celda.

_Decomposer= Decomposer(A, B)
print(_Decomposer[0])
print("\n")
print(_Decomposer[1])
print("\n")
print(_Decomposer[0]@_Decomposer[1])
print("\n")
print(A)
print("\n")
print(A@np.transpose([_Decomposer[2]]))
print("\n")
print(_Decomposer[3])
print("\n\n")

_Factorizer= Factorizer(A, B)
print(_Factorizer[0])
print("\n")
print(_Factorizer[1])
print("\n")
print(_Factorizer[0]@_Factorizer[1])
print("\n")
print(A)
print("\n")
print(A@np.transpose([_Factorizer[2]]))

[[ 1.   0.   0. ]
 [-0.4  1.   0. ]
 [ 0.  -1.   1. ]]


[[ 5. -5.  0.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]


[[ 5. -5.  0.]
 [-2.  3. -1.]
 [ 0. -1.  1.]]


[[ 5 -5  0]
 [-2  3 -1]
 [ 0 -1  1]]


[[nan]
 [nan]
 [nan]]


0.0



[[ 0.92847669  0.25269935  0.93724034]
 [-0.37139068  0.63174837 -0.11026357]
 [ 0.         -0.73282811  0.33079071]]


[[ 5.38516481 -5.75655548  0.37139068]
 [ 0.          1.36457648 -1.36457648]
 [ 0.          0.          0.44105428]]


[[ 5.         -5.          0.41337386]
 [-2.          3.         -1.04863222]
 [ 0.         -1.          1.14589666]]


[[ 5 -5  0]
 [-2  3 -1]
 [ 0 -1  1]]


[[13.88888889]
 [-0.27777778]
 [-5.27777778]]


/tmp/ipykernel_90626/577170648.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = (vector[i] - np.dot(L[i,:], y)) / L[i,i]
/tmp/ipykernel_90626/577170648.py:26: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (y[i] - np.dot(U[i,:], x)) / U[i,i]
/tmp/ipykernel_90626/577170648.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = ((Q.T[i,:]@vector) - np.dot(R[i,:], x)) / R[i,i]
